/** @file LogEncryptor.c

  Hybrid encryption support for AdvancedFileLogger files.

  Copyright (C) Microsoft Corporation. All rights reserved.
  SPDX-License-Identifier: BSD-2-Clause-Patent

**/

#include "AdvancedFileLogger.h"

#include <Library/BaseCryptLib.h>
#include <Library/PrintLib.h>
#include <Protocol/Rng.h>

//
// Optional per-build key material generated by the AdvLoggerEncryptionKeyGen build
// plugin (Common/MU/AdvLoggerPkg/Plugins/AdvLoggerEncryptionKeyGen). When present it
// supplies this build's unique encryption certificate and human-readable Log ID, so
// no platform build code is required. When absent (e.g. the plugin did not run) the
// firmware falls back to PcdAdvancedFileLoggerEncryptionCert and writes no Log ID
// prefix, preserving backwards compatibility.
//
#if defined (__has_include)
  #if __has_include ("AdvLoggerEncryptionKeyGen.h")
    #include "AdvLoggerEncryptionKeyGen.h"
  #endif
#endif

#define ENCRYPTION_WRITE_CHUNK_SIZE  256

STATIC
VOID
WriteUint32Le (
  OUT UINT8   *Buffer,
  IN  UINT32  Value
  )
{
  Buffer[0] = (UINT8)Value;
  Buffer[1] = (UINT8)(Value >> 8);
  Buffer[2] = (UINT8)(Value >> 16);
  Buffer[3] = (UINT8)(Value >> 24);
}

STATIC
EFI_STATUS
GetEncryptionCert (
  OUT CONST UINT8  **CertBuffer,
  OUT UINTN        *CertSize
  )
{
  if ((CertBuffer == NULL) || (CertSize == NULL)) {
    return EFI_INVALID_PARAMETER;
  }

 #ifdef ADV_LOGGER_GEN_ENCRYPTION_CERT
  //
  // Per-build certificate supplied by the AdvLoggerEncryptionKeyGen build plugin.
  //
  *CertBuffer = mAdvLoggerGenEncryptionCert;
  *CertSize   = sizeof (mAdvLoggerGenEncryptionCert);
 #else
  *CertBuffer = (CONST UINT8 *)FixedPcdGetPtr (PcdAdvancedFileLoggerEncryptionCert);
  *CertSize   = FixedPcdGetSize (PcdAdvancedFileLoggerEncryptionCert);
 #endif

  if ((*CertBuffer == NULL) || (*CertSize <= 1)) {
    return EFI_NOT_FOUND;
  }

  return EFI_SUCCESS;
}

STATIC
EFI_STATUS
GetStrongRandomBytes (
  OUT UINT8  *Buffer,
  IN  UINTN  BufferSize
  )
{
  EFI_STATUS        Status;
  EFI_RNG_PROTOCOL  *RngProtocol;
  UINT8             *CryptoRandom;
  UINTN             Index;
  BOOLEAN           HaveCryptoRandom;

  if ((Buffer == NULL) || (BufferSize == 0)) {
    return EFI_INVALID_PARAMETER;
  }

  RngProtocol = NULL;
  Status      = gBS->LocateProtocol (&gEfiRngProtocolGuid, NULL, (VOID **)&RngProtocol);
  if (EFI_ERROR (Status) || (RngProtocol == NULL)) {
    DEBUG ((DEBUG_ERROR, "%a: EFI_RNG_PROTOCOL unavailable; refusing to generate log encryption material: %r\n", __FUNCTION__, Status));
    return EFI_SECURITY_VIOLATION;
  }

  Status = RngProtocol->GetRNG (RngProtocol, &gEfiRngAlgorithmRaw, BufferSize, Buffer);
  if (EFI_ERROR (Status)) {
    DEBUG ((DEBUG_ERROR, "%a: EFI_RNG_ALGORITHM_RAW unavailable; refusing to generate log encryption material: %r\n", __FUNCTION__, Status));
    return EFI_SECURITY_VIOLATION;
  }

  CryptoRandom     = AllocatePool (BufferSize);
  HaveCryptoRandom = FALSE;
  if (CryptoRandom != NULL) {
    HaveCryptoRandom = RandomBytes (CryptoRandom, BufferSize);
    if (HaveCryptoRandom) {
      for (Index = 0; Index < BufferSize; ++Index) {
        Buffer[Index] ^= CryptoRandom[Index];
      }
    } else {
      DEBUG ((DEBUG_WARN, "%a: Crypto RandomBytes failed; using EFI_RNG_ALGORITHM_RAW output only\n", __FUNCTION__));
    }

    ZeroMem (CryptoRandom, BufferSize);
    FreePool (CryptoRandom);
  } else {
    DEBUG ((DEBUG_WARN, "%a: Unable to allocate RandomBytes mix buffer; using EFI_RNG_ALGORITHM_RAW output only\n", __FUNCTION__));
  }

  return EFI_SUCCESS;
}

STATIC
EFI_STATUS
WrapKeys (
  IN OUT ADVANCED_FILE_LOGGER_ENCRYPTION_CONTEXT  *Context
  )
{
  EFI_STATUS   Status;
  CONST UINT8  *CertBuffer;
  UINTN        CertSize;
  VOID         *RsaContext;
  UINT8        *EncryptedData;
  UINTN        EncryptedDataSize;
  BOOLEAN      CryptoStatus;
  UINT8        Secret[ADV_LOG_ENCRYPTION_WRAPPED_SECRET_SIZE];

  CertBuffer        = NULL;
  CertSize          = 0;
  RsaContext        = NULL;
  EncryptedData     = NULL;
  EncryptedDataSize = 0;

  Status = GetEncryptionCert (&CertBuffer, &CertSize);
  if (EFI_ERROR (Status)) {
    DEBUG ((DEBUG_ERROR, "%a: AdvancedFileLogger encryption certificate PCD is empty: %r\n", __FUNCTION__, Status));
    return Status;
  }

  CryptoStatus = RsaGetPublicKeyFromX509 (CertBuffer, CertSize, &RsaContext);
  if (!CryptoStatus || (RsaContext == NULL)) {
    DEBUG ((DEBUG_ERROR, "%a: Failed to extract RSA public key from encryption certificate\n", __FUNCTION__));
    return EFI_SECURITY_VIOLATION;
  }

  //
  // Wrap the concatenation of the two independent random keys (AES key || MAC key).
  //
  CopyMem (Secret, Context->AesKey, AES256_KEY_SIZE);
  CopyMem (Secret + AES256_KEY_SIZE, Context->MacKey, ADV_LOG_ENCRYPTION_MAC_SIZE);

  CryptoStatus = RsaOaepEncrypt (
                   RsaContext,
                   Secret,
                   sizeof (Secret),
                   NULL,
                   0,
                   SHA256_DIGEST_SIZE,
                   &EncryptedData,
                   &EncryptedDataSize
                   );
  RsaFree (RsaContext);
  ZeroMem (Secret, sizeof (Secret));

  if (!CryptoStatus || (EncryptedData == NULL)) {
    DEBUG ((DEBUG_ERROR, "%a: RSA-OAEP key wrap failed\n", __FUNCTION__));
    return EFI_SECURITY_VIOLATION;
  }

  if (EncryptedDataSize != ADV_LOG_ENCRYPTION_WRAPPED_KEY_SIZE) {
    DEBUG ((DEBUG_ERROR, "%a: Unexpected wrapped key length %u\n", __FUNCTION__, (UINT32)EncryptedDataSize));
    FreePool (EncryptedData);
    return EFI_UNSUPPORTED;
  }

  CopyMem (Context->WrappedKey, EncryptedData, ADV_LOG_ENCRYPTION_WRAPPED_KEY_SIZE);
  Context->WrappedKeyLen = ADV_LOG_ENCRYPTION_WRAPPED_KEY_SIZE;
  FreePool (EncryptedData);

  return EFI_SUCCESS;
}

STATIC
EFI_STATUS
WriteNoncePrefix (
  IN     EFI_FILE                                 *File,
  IN OUT ADVANCED_FILE_LOGGER_ENCRYPTION_CONTEXT  *Context
  )
{
  Context->PrefixLen = 0;

 #ifdef ADV_LOGGER_BUILD_NONCE_STRING
  CHAR8       Prefix[256];
  UINTN       PrefixLen;
  UINTN       WriteSize;
  EFI_STATUS  Status;

  PrefixLen = (UINTN)AsciiSPrint (
                       Prefix,
                       sizeof (Prefix),
                       "====== AdvancedFileLogger Encrypted Log ======\n"
                       "Nonce  : %a\n"
                       "Decrypt: DecryptAdvLoggerLogs.py <thisfile> AdvLogger_%a.bin\n"
                       "Encrypted content follows this header.\n"
                       "==============================================\n",
                       ADV_LOGGER_BUILD_NONCE_STRING,
                       ADV_LOGGER_BUILD_NONCE_STRING
                       );
  if (PrefixLen == 0) {
    return EFI_DEVICE_ERROR;
  }

  Status = File->SetPosition (File, 0);
  if (EFI_ERROR (Status)) {
    return Status;
  }

  WriteSize = PrefixLen;
  Status    = File->Write (File, &WriteSize, Prefix);
  if (EFI_ERROR (Status)) {
    return Status;
  }

  if (WriteSize != PrefixLen) {
    return EFI_BAD_BUFFER_SIZE;
  }

  Context->PrefixLen = (UINT32)PrefixLen;
 #endif

  return EFI_SUCCESS;
}

//
// Serialize the plaintext envelope header (Magic..Mac, ADV_LOG_ENCRYPTION_HEADER_SIZE
// bytes). PlaintextLen (offset 36) and Mac (offset 40) are written as zero here; they
// are patched in place later by LogEncryptorUpdatePlaintextLen. Both the on-disk header
// and the running HMAC are built from this exact serialization so their bytes match.
//
STATIC
VOID
BuildEnvelopeHeaderBytes (
  IN  ADVANCED_FILE_LOGGER_ENCRYPTION_CONTEXT  *Context,
  OUT UINT8                                    *Header
  )
{
  ZeroMem (Header, ADV_LOG_ENCRYPTION_HEADER_SIZE);
  CopyMem (Header, ADV_LOG_ENCRYPTION_MAGIC, sizeof (ADV_LOG_ENCRYPTION_MAGIC));
  WriteUint32Le (&Header[8], ADV_LOG_ENCRYPTION_VERSION);
  WriteUint32Le (&Header[12], ADV_LOG_ENCRYPTION_FLAGS);
  CopyMem (&Header[16], Context->Iv, AES_BLOCK_SIZE);
  WriteUint32Le (&Header[32], Context->WrappedKeyLen);
  // Header[36..40) PlaintextLen and Header[40..72) Mac remain zero here.
}

//
// Start the running encrypt-then-MAC HMAC over the authenticated header prefix
// (Magic || Version || Flags || Iv || WrappedKeyLen) followed by the wrapped key.
// Ciphertext bytes are fed incrementally by LogEncryptorWrite.
//
STATIC
EFI_STATUS
InitRunningHmac (
  IN OUT ADVANCED_FILE_LOGGER_ENCRYPTION_CONTEXT  *Context
  )
{
  UINT8  Header[ADV_LOG_ENCRYPTION_HEADER_SIZE];

  Context->HmacFedLen  = 0;
  Context->HmacContext = HmacSha256New ();
  if (Context->HmacContext == NULL) {
    DEBUG ((DEBUG_ERROR, "%a: HmacSha256New failed\n", __FUNCTION__));
    return EFI_OUT_OF_RESOURCES;
  }

  if (!HmacSha256SetKey (Context->HmacContext, Context->MacKey, ADV_LOG_ENCRYPTION_MAC_SIZE)) {
    DEBUG ((DEBUG_ERROR, "%a: HmacSha256SetKey failed\n", __FUNCTION__));
    goto ErrorExit;
  }

  BuildEnvelopeHeaderBytes (Context, Header);

  //
  // Authenticate the header prefix up to (but excluding) PlaintextLen and Mac, i.e.
  // Magic || Version || Flags || Iv || WrappedKeyLen. This mirrors the host decryptor.
  //
  if (!HmacSha256Update (Context->HmacContext, Header, ADV_LOG_ENCRYPTION_PLAINTEXT_LEN_OFFSET)) {
    DEBUG ((DEBUG_ERROR, "%a: HmacSha256Update(header) failed\n", __FUNCTION__));
    goto ErrorExit;
  }

  if (!HmacSha256Update (Context->HmacContext, Context->WrappedKey, Context->WrappedKeyLen)) {
    DEBUG ((DEBUG_ERROR, "%a: HmacSha256Update(wrapped key) failed\n", __FUNCTION__));
    goto ErrorExit;
  }

  return EFI_SUCCESS;

ErrorExit:
  HmacSha256Free (Context->HmacContext);
  Context->HmacContext = NULL;
  return EFI_SECURITY_VIOLATION;
}

STATIC
EFI_STATUS
WriteEnvelopeHeader (
  IN ADVANCED_FILE_LOGGER_ENCRYPTION_CONTEXT  *Context,
  IN EFI_FILE                                 *File
  )
{
  UINT8       Header[ADV_LOG_ENCRYPTION_HEADER_SIZE];
  UINTN       WriteSize;
  EFI_STATUS  Status;

  BuildEnvelopeHeaderBytes (Context, Header);

  Status = File->SetPosition (File, Context->PrefixLen);
  if (EFI_ERROR (Status)) {
    return Status;
  }

  WriteSize = sizeof (Header);
  Status    = File->Write (File, &WriteSize, Header);
  if (EFI_ERROR (Status)) {
    return Status;
  }

  if (WriteSize != sizeof (Header)) {
    return EFI_BAD_BUFFER_SIZE;
  }

  WriteSize = Context->WrappedKeyLen;
  Status    = File->Write (File, &WriteSize, Context->WrappedKey);
  if (EFI_ERROR (Status)) {
    return Status;
  }

  if (WriteSize != Context->WrappedKeyLen) {
    return EFI_BAD_BUFFER_SIZE;
  }

  return EFI_SUCCESS;
}

EFI_STATUS
LogEncryptorEnsureInitialized (
  IN OUT ADVANCED_FILE_LOGGER_ENCRYPTION_CONTEXT  *Context,
  IN     EFI_FILE                                 *File
  )
{
  EFI_STATUS  Status;

  if ((Context == NULL) || (File == NULL)) {
    return EFI_INVALID_PARAMETER;
  }

  if (Context->Initialized) {
    return EFI_SUCCESS;
  }

  ZeroMem (Context, sizeof (*Context));
  Status = GetStrongRandomBytes (Context->AesKey, AES256_KEY_SIZE);
  if (EFI_ERROR (Status)) {
    DEBUG ((DEBUG_ERROR, "%a: Failed to generate AdvancedFileLogger encryption key: %r\n", __FUNCTION__, Status));
    goto ErrorExit;
  }

  Status = GetStrongRandomBytes (Context->MacKey, ADV_LOG_ENCRYPTION_MAC_SIZE);
  if (EFI_ERROR (Status)) {
    DEBUG ((DEBUG_ERROR, "%a: Failed to generate AdvancedFileLogger MAC key: %r\n", __FUNCTION__, Status));
    goto ErrorExit;
  }

  Status = GetStrongRandomBytes (Context->Iv, AES_BLOCK_SIZE);
  if (EFI_ERROR (Status)) {
    DEBUG ((DEBUG_ERROR, "%a: Failed to generate AdvancedFileLogger encryption IV: %r\n", __FUNCTION__, Status));
    goto ErrorExit;
  }

  Aes256Init (&Context->AesContext, Context->AesKey);

  Status = WrapKeys (Context);
  if (EFI_ERROR (Status)) {
    goto ErrorExit;
  }

  Status = WriteNoncePrefix (File, Context);
  if (EFI_ERROR (Status)) {
    DEBUG ((DEBUG_ERROR, "%a: Failed to write AdvancedFileLogger nonce prefix: %r\n", __FUNCTION__, Status));
    goto ErrorExit;
  }

  Context->DataOffset = (UINT64)Context->PrefixLen + ADV_LOG_ENCRYPTION_HEADER_SIZE + Context->WrappedKeyLen;

  Status = InitRunningHmac (Context);
  if (EFI_ERROR (Status)) {
    DEBUG ((DEBUG_ERROR, "%a: Failed to initialize AdvancedFileLogger log MAC: %r\n", __FUNCTION__, Status));
    goto ErrorExit;
  }

  Status = WriteEnvelopeHeader (Context, File);
  if (EFI_ERROR (Status)) {
    DEBUG ((DEBUG_ERROR, "%a: Failed to write AdvancedFileLogger encryption header: %r\n", __FUNCTION__, Status));
    goto ErrorExit;
  }

  Context->Initialized = TRUE;
  return EFI_SUCCESS;

ErrorExit:
  LogEncryptorReset (Context);
  return Status;
}

EFI_STATUS
LogEncryptorWrite (
  IN     EFI_FILE                                 *File,
  IN     ADVANCED_FILE_LOGGER_ENCRYPTION_CONTEXT  *Context,
  IN     UINT64                                   PlaintextOffset,
  IN     CONST VOID                               *Plaintext,
  IN OUT UINTN                                    *PlaintextSize
  )
{
  EFI_STATUS   Status;
  CONST UINT8  *Input;
  UINTN        Remaining;
  UINTN        ChunkSize;
  UINTN        WriteSize;
  UINTN        TotalWritten;
  UINT8        Ciphertext[ENCRYPTION_WRITE_CHUNK_SIZE];

  if ((File == NULL) || (Context == NULL) || (Plaintext == NULL) || (PlaintextSize == NULL) || !Context->Initialized) {
    return EFI_INVALID_PARAMETER;
  }

  //
  // The running encrypt-then-MAC HMAC requires ciphertext to be fed exactly once,
  // strictly in order. The AdvancedFileLogger write model appends contiguously
  // (monotonic CurrentOffset), so PlaintextOffset must equal the number of bytes
  // already fed. Fail closed on any unexpected gap or overlap rather than emit a
  // silently inconsistent MAC.
  //
  if (PlaintextOffset != Context->HmacFedLen) {
    DEBUG ((
      DEBUG_ERROR,
      "%a: Out-of-order encrypted write (offset=%lu, fed=%lu); refusing\n",
      __FUNCTION__,
      PlaintextOffset,
      Context->HmacFedLen
      ));
    return EFI_ACCESS_DENIED;
  }

  Status = File->SetPosition (File, Context->DataOffset + PlaintextOffset);
  if (EFI_ERROR (Status)) {
    return Status;
  }

  Input        = (CONST UINT8 *)Plaintext;
  Remaining    = *PlaintextSize;
  TotalWritten = 0;

  while (Remaining > 0) {
    ChunkSize = (Remaining > sizeof (Ciphertext)) ? sizeof (Ciphertext) : Remaining;
    Aes256CtrCrypt (&Context->AesContext, Context->Iv, PlaintextOffset + TotalWritten, Input, Ciphertext, ChunkSize);

    WriteSize = ChunkSize;
    Status    = File->Write (File, &WriteSize, Ciphertext);
    if (EFI_ERROR (Status)) {
      ZeroMem (Ciphertext, sizeof (Ciphertext));
      *PlaintextSize = TotalWritten;
      return Status;
    }

    if (WriteSize != ChunkSize) {
      ZeroMem (Ciphertext, sizeof (Ciphertext));
      *PlaintextSize = TotalWritten + WriteSize;
      return EFI_BAD_BUFFER_SIZE;
    }

    //
    // Feed the just-written ciphertext into the running HMAC before wiping it.
    //
    if (!HmacSha256Update (Context->HmacContext, Ciphertext, ChunkSize)) {
      ZeroMem (Ciphertext, sizeof (Ciphertext));
      DEBUG ((DEBUG_ERROR, "%a: HmacSha256Update(ciphertext) failed\n", __FUNCTION__));
      *PlaintextSize = TotalWritten;
      return EFI_SECURITY_VIOLATION;
    }

    Context->HmacFedLen += ChunkSize;
    ZeroMem (Ciphertext, sizeof (Ciphertext));

    Input        += ChunkSize;
    Remaining    -= ChunkSize;
    TotalWritten += ChunkSize;
  }

  *PlaintextSize = TotalWritten;
  return EFI_SUCCESS;
}

EFI_STATUS
LogEncryptorUpdatePlaintextLen (
  IN EFI_FILE                                 *File,
  IN ADVANCED_FILE_LOGGER_ENCRYPTION_CONTEXT  *Context,
  IN UINT64                                   PlaintextLen
  )
{
  EFI_STATUS  Status;
  UINT32      PlaintextLen32;
  UINT8       PlaintextLenBytes[sizeof (UINT32)];
  UINT8       Mac[ADV_LOG_ENCRYPTION_MAC_SIZE];
  VOID        *MacSnapshot;
  UINTN       WriteSize;

  if ((File == NULL) || (Context == NULL) || !Context->Initialized || (Context->HmacContext == NULL)) {
    return EFI_INVALID_PARAMETER;
  }

  if (PlaintextLen > MAX_UINT32) {
    return EFI_BAD_BUFFER_SIZE;
  }

  //
  // The MAC snapshot authenticates exactly the ciphertext bytes fed so far, which
  // must equal the plaintext length recorded in the header. If they ever diverge
  // the log would be undecryptable, so fail closed instead of writing a bad MAC.
  //
  if (PlaintextLen != Context->HmacFedLen) {
    DEBUG ((
      DEBUG_ERROR,
      "%a: PlaintextLen %lu != HMAC-fed length %lu; refusing\n",
      __FUNCTION__,
      PlaintextLen,
      Context->HmacFedLen
      ));
    return EFI_ACCESS_DENIED;
  }

  //
  // Finalize a *copy* of the running HMAC so the original context can keep
  // absorbing ciphertext on subsequent flushes.
  //
  MacSnapshot = HmacSha256New ();
  if (MacSnapshot == NULL) {
    return EFI_OUT_OF_RESOURCES;
  }

  if (!HmacSha256Duplicate (Context->HmacContext, MacSnapshot)) {
    HmacSha256Free (MacSnapshot);
    return EFI_SECURITY_VIOLATION;
  }

  if (!HmacSha256Final (MacSnapshot, Mac)) {
    HmacSha256Free (MacSnapshot);
    return EFI_SECURITY_VIOLATION;
  }

  HmacSha256Free (MacSnapshot);

  PlaintextLen32 = (UINT32)PlaintextLen;
  WriteUint32Le (PlaintextLenBytes, PlaintextLen32);

  Status = File->SetPosition (File, (UINT64)Context->PrefixLen + ADV_LOG_ENCRYPTION_PLAINTEXT_LEN_OFFSET);
  if (EFI_ERROR (Status)) {
    return Status;
  }

  WriteSize = sizeof (PlaintextLenBytes);
  Status    = File->Write (File, &WriteSize, PlaintextLenBytes);
  if (EFI_ERROR (Status)) {
    return Status;
  }

  if (WriteSize != sizeof (PlaintextLenBytes)) {
    return EFI_BAD_BUFFER_SIZE;
  }

  Status = File->SetPosition (File, (UINT64)Context->PrefixLen + ADV_LOG_ENCRYPTION_MAC_OFFSET);
  if (EFI_ERROR (Status)) {
    return Status;
  }

  WriteSize = sizeof (Mac);
  Status    = File->Write (File, &WriteSize, Mac);
  if (EFI_ERROR (Status)) {
    return Status;
  }

  if (WriteSize != sizeof (Mac)) {
    return EFI_BAD_BUFFER_SIZE;
  }

  return EFI_SUCCESS;
}

VOID
LogEncryptorReset (
  IN OUT ADVANCED_FILE_LOGGER_ENCRYPTION_CONTEXT  *Context
  )
{
  if (Context != NULL) {
    if (Context->HmacContext != NULL) {
      HmacSha256Free (Context->HmacContext);
      Context->HmacContext = NULL;
    }

    ZeroMem (Context, sizeof (*Context));
  }
}
